### ISSUE TITLE
Next Page Buttons Skip erratically

### ISSUE THREAD

**Issue by Elfykins** [FluffyFishGames/ACNHDesignPatternEditor#55]
When using the import option and selecting ones from the exchange, when you click the arrows it suddenly scrolls through everything at an insane rate and skips pages....this makes finding anything impossible.

**Comment by FluffyFishGames** [comment]
Can you confirm this still happens in 1.0.1?

**Comment by Kyraktos** [comment]
Looks like the issue seems to be fixed! At least on an initial test, it looks to be good! :)

**Comment by FluffyFishGames** [comment]
Dunno how I fixed it tho but I am happy its fixed. Maybe the new import flow fixed something. Closing this :)

**Comment by TotalKnockouttt** [comment]
I really hate to do this, as I hate being a pest, but I am still having this issue! No matter what I do, it skips pages! I cannot use this at all and I am so beyond frustrated because nothing I do works!

**Comment by TotalKnockouttt** [comment]
Update! I figured it out, it was a controller issue my baaad!!
